
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Wed Feb 21 16:57:51 CST 2018
//----------------------------------------------------

package Analizadores_CCSS;

/** CUP generated class containing symbol constants. */
public class SimbolosCCSS {
  /* terminals */
  public static final int pr_opaque = 33;
  public static final int pr_formato = 19;
  public static final int asig = 7;
  public static final int coma = 12;
  public static final int pr_justificado = 18;
  public static final int pr_negrilla = 20;
  public static final int pr_cursiva = 23;
  public static final int pr_fondoelemento = 29;
  public static final int cor_c = 3;
  public static final int identificador = 42;
  public static final int cor_a = 2;
  public static final int saltos = 41;
  public static final int pr_true = 21;
  public static final int ptodo = 39;
  public static final int pr_letra = 27;
  public static final int pr_tamtext = 28;
  public static final int otro_simb = 46;
  public static final int numero = 40;
  public static final int pr_grupo = 35;
  public static final int pr_alineado = 13;
  public static final int simb = 47;
  public static final int menos = 11;
  public static final int pr_vertical = 38;
  public static final int pr_derecha = 16;
  public static final int cadena2 = 45;
  public static final int EOF = 0;
  public static final int mas = 9;
  public static final int error = 1;
  public static final int pr_minuscula = 25;
  public static final int pr_autoredimension = 30;
  public static final int por = 8;
  public static final int pr_colortext = 34;
  public static final int pr_izquierda = 15;
  public static final int pr_visible = 31;
  public static final int texto = 43;
  public static final int pr_capital = 26;
  public static final int pr_id = 36;
  public static final int pr_centrado = 17;
  public static final int pr_texto = 14;
  public static final int pr_false = 22;
  public static final int div = 10;
  public static final int pr_mayuscula = 24;
  public static final int pr_borde = 32;
  public static final int pr_parC = 5;
  public static final int pr_parA = 4;
  public static final int cadena = 44;
  public static final int pr_horizontal = 37;
  public static final int p_coma = 6;
}

