
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Fri Mar 02 00:12:57 CST 2018
//----------------------------------------------------

package Analizador_CJS;

/** CUP generated class containing symbol constants. */
public class SimbolosCJS {
  /* terminals */
  public static final int pr_sino = 26;
  public static final int pr_imprimir = 30;
  public static final int pr_conteo = 44;
  public static final int llave_c = 12;
  public static final int pr_dimv = 31;
  public static final int llave_a = 11;
  public static final int coma = 18;
  public static final int igual = 2;
  public static final int identificador = 46;
  public static final int pr_true = 48;
  public static final int ptodo = 39;
  public static final int pr_selecciona = 38;
  public static final int dos_puntos = 17;
  public static final int pr_not = 10;
  public static final int pr_and = 8;
  public static final int numero = 45;
  public static final int pr_mientras = 28;
  public static final int pr_detener = 33;
  public static final int menos = 20;
  public static final int menor = 4;
  public static final int EOF = 0;
  public static final int mayor_igual = 6;
  public static final int mas = 19;
  public static final int pr_si = 25;
  public static final int error = 1;
  public static final int mayor = 5;
  public static final int pr_setelemento = 37;
  public static final int por = 21;
  public static final int punto = 15;
  public static final int pr_para = 27;
  public static final int menor_igual = 7;
  public static final int pr_documento = 34;
  public static final int pr_defecto = 41;
  public static final int incremento = 24;
  public static final int pr_atexto = 36;
  public static final int pr_or = 9;
  public static final int diferente = 3;
  public static final int pr_caso = 40;
  public static final int decremento = 23;
  public static final int pr_observador = 35;
  public static final int pr_mensaje = 42;
  public static final int pr_false = 49;
  public static final int pr_funcion = 29;
  public static final int div = 22;
  public static final int pr_retornar = 32;
  public static final int pr_obtener = 43;
  public static final int pr_parC = 14;
  public static final int pr_parA = 13;
  public static final int cadena = 47;
  public static final int p_coma = 16;
}

